name: Java application
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: cloning github repository
        uses: actions/checkout@v7.0.0

      - name: compile java project
        shell: cmd
        run: javac Test.java

      - name: execute java project
        shell: cmd
        run: java Test
        

      

     
